/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package http_server.app;

import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalToIgnoringCase;


class MessageUtilsTest {
    @Test void testGetMessage() {
        assertThat((MessageUtils.getMessage()), equalToIgnoringCase("Hello      World!"));
    }
}
