/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package http_server.client;

public class App {
    public static void main(String[] args) {
        System.out.println("hello");
    }
}
