/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package http_server;

import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.notNullValue;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertThat(classUnderTest.getGreeting(), notNullValue());
    }
}
