name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: "8.1.1"
          arguments: build

      - name: Run Checkstyle with filter
        uses: iwata-n/actions-checkstyle@v1.0.0

      - name: Build with Gradle wrapper
        run: ./gradlew build

      - name: Run server in background
        run: java -jar build/libs/app.jar &

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124
        with:
          ruby-version: '2.7'

      - name: Run Spinach acceptance tests
        run: |
          cd http_server_spec
          bundle install
          rake test:implemented
        working-directory: http_server/http_server_spec